name: ai_app_ollama
description: A Dart Plugin which can be used to make api request to Ollama AI on localhost
version: 1.0.0
homepage: https://ollama.ai/
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
